#pragma kernel KernelGroupThread

RWStructuredBuffer<int> _Buffer;

[numthreads(6,1,1)]
void KernelGroupThread (uint3 groupID       : SV_GroupID,
                        uint3 groupThreadID : SV_GroupThreadID)
{
    // グループIDはcsで指定、グループスレッドIDはこっちで指定
    // _Buffer[groupID.x * 4 + groupThreadID.x] = groupID.x * 4 + groupThreadID.x; // 0~7
    _Buffer[groupID.x * 6 + groupThreadID.x] = groupID.x * 6 + groupThreadID.x; // 0~11
}
